package com.gridgain.eav.startup;

import org.apache.ignite.Ignition;

/** This file was generated by Ignite Web Console (08/27/2020, 13:47) **/
public class ServerNodeSpringStartup {
    /**
     * Start up node with specified configuration.
     * 
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {
        Ignition.start("eav-server.xml");
    }
}