package com.gridgain.eav.model;

import java.io.Serializable;

/**
 * Attribute definition.
 * 
 * This file was generated by Ignite Web Console (08/27/2020, 13:47)
 **/
public class Attribute implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for datatype. */
    private String datatype;

    /** Value for description. */
    private String description;

    /** Empty constructor. **/
    public Attribute() {
        // No-op.
    }

    /** Full constructor. **/
    public Attribute(String datatype,
        String description) {
        this.datatype = datatype;
        this.description = description;
    }

    /**
     * Gets datatype
     * 
     * @return Value for datatype.
     **/
    public String getDatatype() {
        return datatype;
    }

    /**
     * Sets datatype
     * 
     * @param datatype New value for datatype.
     **/
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Attribute))
            return false;
        
        Attribute that = (Attribute)o;

        if (datatype != null ? !datatype.equals(that.datatype) : that.datatype != null)
            return false;
        

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = datatype != null ? datatype.hashCode() : 0;

        res = 31 * res + (description != null ? description.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Attribute [" + 
            "datatype=" + datatype + ", " + 
            "description=" + description +
        "]";
    }
}