package com.gridgain.eav.model;

import java.io.Serializable;
import org.apache.ignite.cache.affinity.AffinityKeyMapped;

/**
 * EntityAttributeKey definition.
 * 
 * This file was generated by Ignite Web Console (08/27/2020, 13:47)
 **/
public class EntityAttributeKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for entity. */
    @AffinityKeyMapped
    private String entity;

    /** Value for attr. */
    private String attr;

    /** Empty constructor. **/
    public EntityAttributeKey() {
        // No-op.
    }

    /** Full constructor. **/
    public EntityAttributeKey(String entity,
        String attr) {
        this.entity = entity;
        this.attr = attr;
    }

    /**
     * Gets entity
     * 
     * @return Value for entity.
     **/
    public String getEntity() {
        return entity;
    }

    /**
     * Sets entity
     * 
     * @param entity New value for entity.
     **/
    public void setEntity(String entity) {
        this.entity = entity;
    }

    /**
     * Gets attr
     * 
     * @return Value for attr.
     **/
    public String getAttr() {
        return attr;
    }

    /**
     * Sets attr
     * 
     * @param attr New value for attr.
     **/
    public void setAttr(String attr) {
        this.attr = attr;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof EntityAttributeKey))
            return false;
        
        EntityAttributeKey that = (EntityAttributeKey)o;

        if (entity != null ? !entity.equals(that.entity) : that.entity != null)
            return false;
        

        if (attr != null ? !attr.equals(that.attr) : that.attr != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = entity != null ? entity.hashCode() : 0;

        res = 31 * res + (attr != null ? attr.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "EntityAttributeKey [" + 
            "entity=" + entity + ", " + 
            "attr=" + attr +
        "]";
    }
}