package com.gridgain.eav.model;

import java.io.Serializable;

/**
 * Entity definition.
 * 
 * This file was generated by Ignite Web Console (08/27/2020, 13:47)
 **/
public class Entity implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for description. */
    private String description;

    /** Value for ontology. */
    private String ontology;

    /** Empty constructor. **/
    public Entity() {
        // No-op.
    }

    /** Full constructor. **/
    public Entity(String description,
        String ontology) {
        this.description = description;
        this.ontology = ontology;
    }

    /**
     * Gets description
     * 
     * @return Value for description.
     **/
    public String getDescription() {
        return description;
    }

    /**
     * Sets description
     * 
     * @param description New value for description.
     **/
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Gets ontology
     * 
     * @return Value for ontology.
     **/
    public String getOntology() {
        return ontology;
    }

    /**
     * Sets ontology
     * 
     * @param ontology New value for ontology.
     **/
    public void setOntology(String ontology) {
        this.ontology = ontology;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Entity))
            return false;
        
        Entity that = (Entity)o;

        if (description != null ? !description.equals(that.description) : that.description != null)
            return false;
        

        if (ontology != null ? !ontology.equals(that.ontology) : that.ontology != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = description != null ? description.hashCode() : 0;

        res = 31 * res + (ontology != null ? ontology.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Entity [" + 
            "description=" + description + ", " + 
            "ontology=" + ontology +
        "]";
    }
}