package com.gridgain.eav.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * EntityAttribute definition.
 * 
 * This file was generated by Ignite Web Console (08/27/2020, 13:47)
 **/
public class EntityAttribute implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for sequence. */
    private BigDecimal sequence;

    /** Empty constructor. **/
    public EntityAttribute() {
        // No-op.
    }

    /** Full constructor. **/
    public EntityAttribute(BigDecimal sequence) {
        this.sequence = sequence;
    }

    /**
     * Gets sequence
     * 
     * @return Value for sequence.
     **/
    public BigDecimal getSequence() {
        return sequence;
    }

    /**
     * Sets sequence
     * 
     * @param sequence New value for sequence.
     **/
    public void setSequence(BigDecimal sequence) {
        this.sequence = sequence;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof EntityAttribute))
            return false;
        
        EntityAttribute that = (EntityAttribute)o;

        if (sequence != null ? !sequence.equals(that.sequence) : that.sequence != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = sequence != null ? sequence.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "EntityAttribute [" + 
            "sequence=" + sequence +
        "]";
    }
}